export const GOOGLE_FONTS = [
  'Inter',
  'Roboto',
  'Open Sans',
  'Lato',
  'Montserrat',
  'Poppins',
  'Raleway',
  'Nunito',
  'Playfair Display',
  'Merriweather',
  'Source Sans 3',
  'PT Sans',
  'Noto Sans',
  'Ubuntu',
  'Oswald',
  'Rubik',
  'Work Sans',
  'Fira Sans',
  'Quicksand',
  'Barlow',
  'DM Sans',
  'Mulish',
  'Manrope',
  'Space Grotesk',
  'Outfit',
  'Plus Jakarta Sans',
  'Sora',
  'Lexend',
  'Cabin',
  'Karla',
  'Libre Baskerville',
  'Lora',
  'EB Garamond',
  'Crimson Text',
  'Bitter',
  'IBM Plex Sans',
  'IBM Plex Mono',
  'JetBrains Mono',
  'Fira Code',
  'Source Code Pro',
  'Roboto Mono',
  'Space Mono',
  'Inconsolata',
  'PT Serif',
  'Noto Serif',
  'Cormorant Garamond',
  'Josefin Sans',
  'Archivo',
  'Red Hat Display',
  'Satoshi',
] as const;

export const FONT_SIZE_OPTIONS = [
  '72', '56', '48', '36', '32', '28', '24', '20', '18', '16', '14', '12',
] as const;

export const FONT_WEIGHT_OPTIONS = [
  { value: 100, label: '100 - Thin' },
  { value: 200, label: '200 - Extra Light' },
  { value: 300, label: '300 - Light' },
  { value: 400, label: '400 - Regular' },
  { value: 500, label: '500 - Medium' },
  { value: 600, label: '600 - Semibold' },
  { value: 700, label: '700 - Bold' },
  { value: 800, label: '800 - Extra Bold' },
  { value: 900, label: '900 - Black' },
] as const;
